backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:

# ========================
# Ashaar
# ========================

  - name: "ashaar"
    label: "Ashaar"
    files:
      - file: "content/ashaar.json"
        label: "Ashaar"
        name: "ashaar"
        fields:
          - label: "Ashaar"
            name: "items"
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "text" }


# ========================
# Ghazal
# ========================

  - name: "ghazal"
    label: "Ghazal"
    files:
      - file: "content/ghazal.json"
        label: "Ghazal"
        name: "ghazal"
        fields:
          - label: "Ghazal"
            name: "items"
            widget: "list"
            fields:

              - label: "Category"
                name: "category"
                widget: "select"
                options:
                  - Bab-e-Intezaar
                  - Bab-e-Hijr
                  - Bab-e-Karb
                  - Bab-e-Be-Naam
                  - Bab-e-Tasawwur
                  - Bab-e-Falsafa
                  - Bab-e-Iqraar
                  - Bab-e-Ibtida

              - { label: "Text", name: "text", widget: "text" }


# ========================
# Rubai
# ========================

  - name: "rubai"
    label: "Rubai"
    files:
      - file: "content/rubai.json"
        label: "Rubai"
        name: "rubai"
        fields:
          - label: "Rubai"
            name: "items"
            widget: "list"
            fields:
              - { label: "Text", name: "text", widget: "text" }